const IMAGES = {
    image1 : new URL('./man.jpg', import.meta.url).href,
    image2 : new URL('./woman.jpg', import.meta.url).href,
    image3 : new URL('./101.png', import.meta.url).href,
    image4 : new URL('./person-fill.svg', import.meta.url).href,
    image5 : new URL('./cart.svg', import.meta.url).href,
    image6 : new URL('./about101.jpg', import.meta.url).href,
    image7 : new URL('./fullCatalog.jpg', import.meta.url).href,
    image8 : new URL('./womanCatalog.jpg', import.meta.url).href,
    image9 : new URL('./manCatalog.jpg', import.meta.url).href,
    image10 : new URL('./trash.svg', import.meta.url).href,
    VideoUomo : new URL('./Video/uomo.mp4', import.meta.url).href,
    VideoDonna : new URL('./Video/donna.mp4', import.meta.url).href,
    Abby1 : new URL('./LineaAmber/AbbyArancio.jpg', import.meta.url).href,
    Abby1_top : new URL('./LineaAmber/AbbyArancioTop.jpg', import.meta.url).href,
    Abby2 : new URL('./LineaAmber/AbbyLime.jpg', import.meta.url).href,
    Abby2_top : new URL('./LineaAmber/AbbyLimeTop.jpg', import.meta.url).href,
    Abby3 : new URL('./LineaAmber/AlishaNavy.jpg', import.meta.url).href,
    Abby3_top : new URL('./LineaAmber/AlishaNavyTop.jpg', import.meta.url).href,
    Abby4 : new URL('./LineaAmber/AlishaCamelia.jpg', import.meta.url).href,
    Abby4_top : new URL('./LineaAmber/AlishaCameliaTop.jpg', import.meta.url).href,
    Betsy1 : new URL('./LineaBass/BetsyFuxia.jpg', import.meta.url).href,
    Betsy1_top : new URL('./LineaBass/BetsyFuxiaTop.jpg', import.meta.url).href,
    Betsy2 : new URL('./LineaBass/BonnyArancio.jpg', import.meta.url).href,
    Betsy2_top : new URL('./LineaBass/BonnyArancioTop.jpg', import.meta.url).href,
    Betsy3 : new URL('./LineaBass/BonnyCamelia.jpg', import.meta.url).href,
    Betsy3_top : new URL('./LineaBass/BonnyCameliaTop.jpg', import.meta.url).href,
    Smith1 : new URL('./LineaSmith/SlyDenim.jpg', import.meta.url).href,
    Smith1_top : new URL('./LineaSmith/SlyDenimTop.jpg', import.meta.url).href,
    Smith2 : new URL('./LineaSmith/SlyAntik.jpg', import.meta.url).href,
    Smith2_top : new URL('./LineaSmith/SlyAntikTop.jpg', import.meta.url).href,
    Smith3 : new URL('./LineaSmith/SybilOro.jpg', import.meta.url).href,
    Smith3_top : new URL('./LineaSmith/SybilOroTop.jpg', import.meta.url).href,
    Glenn1 : new URL('./LineaGlenn/GipsyArancio.jpg', import.meta.url).href,
    Glenn1_top : new URL('./LineaGlenn/GipsyArancioTop.jpg', import.meta.url).href,
    Glenn2 : new URL('./LineaGlenn/GloveNero.jpg', import.meta.url).href,
    Glenn2_top : new URL('./LineaGlenn/GloveNeroTop.jpg', import.meta.url).href,
    Glenn3 : new URL('./LineaGlenn/GlemFuxia.jpg', import.meta.url).href,
    Glenn3_top : new URL('./LineaGlenn/GlemFuxiaTop.jpg', import.meta.url).href,
    Beige1 : new URL('./LineaBeige/GinnyBrown.jpg', import.meta.url).href,
    Beige1_cover : new URL('./LineaBeige/GinnyBrownCover.jpg', import.meta.url).href,
    Beige2 : new URL('./LineaBeige/GinnySand.jpg', import.meta.url).href,
    Beige2_cover : new URL('./LineaBeige/GinnySandCover.jpg', import.meta.url).href,
    Carpet1 : new URL('./LineaCarpet/GinnyBlack.jpg', import.meta.url).href,
    Carpet1_cover : new URL('./LineaCarpet/GinnyBlackCover.jpg', import.meta.url).href,
    Carpet2 : new URL('./LineaCarpet/GinnyRed.jpg', import.meta.url).href,
    Carpet2_cover : new URL('./LineaCarpet/GinnyRedCover.jpg', import.meta.url).href,
    Classic1 : new URL('./LineaClassic/GinnyBlu.jpg', import.meta.url).href,
    Classic1_cover : new URL('./LineaClassic/GinnyBluCover.jpg', import.meta.url).href,
    Classic2 : new URL('./LineaClassic/GinnyWhite.jpg', import.meta.url).href,
    Classic2_cover : new URL('./LineaClassic/GinnyWhiteCover.jpg', import.meta.url).href,
    X1 : new URL('./LineaXStyle/SkyBrown.jpg', import.meta.url).href,
    X1_cover : new URL('./LineaXStyle/SkyBrownCover.jpg', import.meta.url).href,
    X2 : new URL('./LineaXStyle/SkyGreen.jpg', import.meta.url).href,
    X2_cover : new URL('./LineaXStyle/SkyGreenCover.jpg', import.meta.url).href,
    LineaAmber: new URL('./copertineLinee/donnaBeige.jpg', import.meta.url).href,
    LineaBass: new URL('./copertineLinee/donnaBianco.jpg', import.meta.url).href,
    LineaFloyd: new URL('./copertineLinee/donnaNero.jpg', import.meta.url).href,
    LineaGlenn: new URL('./copertineLinee/donnaRosso.jpg', import.meta.url).href,
    LineaClassic: new URL('./copertineLinee/uomoMarrone.jpg', import.meta.url).href,
    LineaXStyle: new URL('./copertineLinee/uomoNero.jpg', import.meta.url).href,
    LineaCarpet: new URL('./copertineLinee/uomoBianco.jpg', import.meta.url).href,
    LineaBeige: new URL('./copertineLinee/uomoBeige.jpg', import.meta.url).href,
}
export default IMAGES